

import java.text.DecimalFormat;

/*
 * Class Production Worker which extends class Employee
 * Prodcution Workers have hourly salary
 */

/**
 *
 * @author VH
 * Complete comments are NOT provided
 *
 * Inherits static fields
 *   Random r
 *   NumberFormat CURRENCY
 */
public class ProductionWorker extends Employee {
    //Object member fields
    private double hourlyRate;

    // Class constants
    private static final double MIN_RATE = 6.0;
    private static final double MAX_RATE = 50.0;
   

    // Default Constructor -- creates Production Worker with Random Data
    public ProductionWorker() {
        super();
        this.hourlyRate = MIN_RATE + r.nextDouble() * (MAX_RATE - MIN_RATE);
    }

    //Class Constructor
    public ProductionWorker(String name, String id, 
            int year, double ratePerHour) throws InvalidEmployeeException 
            {
        
        super(name, id, year);

        hourlyRate = MIN_RATE;
        if (ratePerHour >= MIN_RATE && ratePerHour <= MAX_RATE) {
            hourlyRate = ratePerHour;
        }
    }
    public ProductionWorker(String name, String id, 
            int year) throws InvalidEmployeeException 
            {
        
        super(name, id, year);

        hourlyRate = MIN_RATE + r.nextDouble() * (MAX_RATE - MIN_RATE);
      
        
    }
    // ACCESSORS
    public double getRate() {
        return hourlyRate;
    }

    // MUTATOR
    /**
     * method that sets the hourlySalary
     */
    public void setRate(double ratePerHour) {
        if (ratePerHour >= MIN_RATE && ratePerHour <= MAX_RATE) {
            hourlyRate = ratePerHour;
        }
    }

    /**
     * toString() method that returns the hourlySalary,yearlySalary,
     *  eName,eNumber,hireYear,and weeklySalary
     */
    @Override
    public String toString() 
    {
    	
        return "Production Worker "+super.toString() + "\n" 
               +"Hourly Rate "+CURRENCY.format(hourlyRate);
    }
    
    
    //for read/Write purposes
    public String toStringTwo() 
    {
    	
        return  "Production Worker "+ super.toStringTwo() + " " 
                +format.format(hourlyRate)+ReadFile.DELIMITER;
    }
    
    
    /**
     * Equals method
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        
        // check if this object has the same parent values
        if (!super.equals(obj))
        {
            return false;
        }
        
        final ProductionWorker other = (ProductionWorker) obj;
        if (Double.doubleToLongBits(this.hourlyRate) != 
                Double.doubleToLongBits(other.hourlyRate)) {
            return false;
        }
        return true;
    }
   
    // Automatically Generated by NetBeans
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + 
                (int) (Double.doubleToLongBits(this.hourlyRate) ^ 
                (Double.doubleToLongBits(this.hourlyRate) >>> 32));
        return hash;
    }

    // Implementing abstract methods
    public String getSalary() {
        return "" + CURRENCY.format(hourlyRate) + "per hour";
    }
}